In [1]:
#importing important libraries 
import warnings
warnings.simplefilter("ignore")
warnings.filterwarnings("ignore")
import requests
from bs4 import BeautifulSoup
import selenium
from selenium import webdriver
import pandas as pd
import time
from selenium.common.exceptions import NoSuchElementException, StaleElementReferenceException, ElementClickInterceptedException

1. Scrape the details of most viewed videos on YouTube from Wikipedia. 
Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos You need to find following details:
A) Rank
B) Name
C) Atist
D) Upload date
E) Views

In [2]:
url = "https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos"
driver = webdriver.Chrome('D:/Installed Software  2/chromedriver.exe')
driver.get(url)
driver.maximize_window()
driver.find_element_by_xpath("//b").click()
records = []
for row in driver.find_elements_by_xpath("(//table[@class='wikitable sortable jquery-tablesorter'])[1]//tr")[1:-1]:
    temp = ''
    for element in row.find_elements_by_xpath(".//td"):        
        temp += element.text + '|'
    records.append(temp.split('|')[:-2])

df = pd.DataFrame(records, columns=['Rank', 'Video_Name', 'Artist_Name', 'Views_in_Billions', 'Upload_Date'])

arranged_cols = ['Rank', 'Video_Name', 'Artist_Name', 'Upload_Date', 'Views_in_Billions']

df.Video_Name = df.Video_Name.apply(lambda x:x[:-4].strip('"'))
df = df[arranged_cols]
df

,Rank,Video_Name,Artist_Name,Upload_Date,Views_in_Billions
0,1.,Baby Shark Dance,Pinkfong Baby Shark - Kids' Songs & Stories,"June 17, 2016",9.89
1,2.,Despacito,Luis Fonsi,"January 12, 2017",7.67
2,3.,Johny Johny Yes Papa,LooLoo Kids,"October 8, 2016",6.04
3,4.,Shape of You,Ed Sheeran,"January 30, 2017",5.56
4,5.,See You Again,Wiz Khalifa,"April 6, 2015",5.36
5,6.,Bath Song,Cocomelon – Nursery Rhymes,"May 2, 2018",4.78
6,7.,Learning Colors – Colorful Eggs on a Farm,Miroshka TV,"February 27, 2018",4.54
7,8.,Masha and the Bear – Recipe for Disaster,Get Movies,"January 31, 2012",4.47
8,9.,Uptown Funk,Mark Ronson,"November 19, 2014",4.40
9,10.,Phonics Song with Two Words,ChuChu TV,"March 6, 2014",4.37
10,11.,Gangnam Style,Psy,"July 15, 2012",4.28
11,12.,Dame Tu Cosita,El Chombo,"April 5, 2018",3.77
12,13.,Sugar,Maroon 5,"January 14, 2015",3.61
13,14.,Sorry,Justin Bieber,"October 22, 2015",3.50
14,15.,Roar,Katy Perry,"September 5, 2013",3.49
15,16.,Counting Stars,OneRepublic,"May 31, 2013",3.47
16,17.,Wheels on the Bus,Cocomelon – Nursery Rhymes,"May 24, 2018",3.43
17,18.,Thinking Out Loud,Ed Sheeran,"October 7, 2014",3.38
18,19.,Girls Like You,Maroon 5,"May 31, 2018",3.20
19,20.,Faded,Alan Walker,"December 3, 2015",3.20
20,21.,Dark Horse,Katy Perry,"February 20, 2014",3.19
21,22.,Axel F,Crazy Frog,"June 16, 2009",3.14
22,23.,Bailando,Enrique Iglesias,"April 11, 2014",3.14
23,24.,Let Her Go,Passenger,"July 25, 2012",3.14
24,25.,Lean On,Major Lazer,"March 22, 2015",3.14
25,26.,Shake It Off,Taylor Swift,"August 18, 2014",3.13
26,27.,Perfect,Ed Sheeran,"November 9, 2017",3.04
27,28.,Mi Gente,J Balvin,"June 29, 2017",3.02
28,29.,Waka Waka (This Time for Africa),Shakira,"June 4, 2010",3.01
29,30.,Baa Baa Black Sheep,Cocomelon – Nursery Rhymes,"June 25, 2018",3.00

2. Scrape the details team India’s international fixtures from bcci.tv.
Url = https://www.bcci.tv/.
You need to find following details:
A) Match title (I.e. 1st ODI)
B) Series
C) Place
D) Date
E) Time
Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [4]:
url = "https://www.bcci.tv/"
page = requests.get(url)
print("Legality Response number from our URL is:", page) # to show the response output from the webpage
soup = BeautifulSoup(page.content)

driver = webdriver.Chrome('D:/Installed Software  2/chromedriver.exe')
driver.get(url)
driver.maximize_window()

btn=driver.find_element_by_xpath("//div[@class = 'navigation__drop-down drop-down drop-down--reveal-on-hover']/div/ul/li/a")
driver.get(btn.get_attribute("href"))
time.sleep(3)

# Empty lists
match_title=[]
series=[]
place=[]
date=[]
matchtime=[]
datetime=[]

for i in driver.find_elements_by_xpath("//div[@class='fixture__format-strip']/span[@class='u-unskewed-text fixture__format']"):
    match_title.append(i.text)
    
for i in driver.find_elements_by_xpath("//div[@class='fixture__format-strip']/span[@class='u-unskewed-text fixture__tournament-label u-truncated']"):
    series.append(i.text)

for i in driver.find_elements_by_xpath("//div[@class='fixture__description u-unskewed-text']/p/span"):
    place.append(i.text)
    
for i in driver.find_elements_by_xpath("//div[@class='fixture__datetime desktop-only']"):
    datetime.append(i.text.replace('\n',' '))
    
date=[i.split(' ',3)[:3] for i in datetime]
date=[' '.join(i) for i in date]
matchtime=[i.split(' ',3)[-1] for i in datetime]

# Creating data frame
matches_data=pd.DataFrame({'Match Title': match_title,
                          "Series": series,
                          "Place": place,
                          "Date": date,
                          "Time": matchtime})
matches_data

Legality Response number from our URL is: <Response [200]>

,Match Title,Series,Place,Date,Time
0,TEST,SOUTH AFRICA V INDIA 2021/2022,"Newlands, Cape Town",Tuesday 11 JANUARY,14:00 IST
1,ODI,SOUTH AFRICA V INDIA 2021/2022,"Boland Park, Paarl",Wednesday 19 JANUARY,14:00 IST
2,T20I,SOUTH AFRICA V INDIA 2021/2022,"Newlands, Cape Town",Wednesday 19 JANUARY,19:30 IST
3,ODI,SOUTH AFRICA V INDIA 2021/2022,"Boland Park, Paarl",Friday 21 JANUARY,14:00 IST
4,T20I,SOUTH AFRICA V INDIA 2021/2022,"Newlands, Cape Town",Friday 21 JANUARY,19:30 IST
5,ODI,SOUTH AFRICA V INDIA 2021/2022,"Newlands, Cape Town",Sunday 23 JANUARY,14:00 IST
6,T20I,SOUTH AFRICA V INDIA 2021/2022,"Boland Park, Paarl",Sunday 23 JANUARY,19:30 IST
7,T20I,SOUTH AFRICA V INDIA 2021/2022,"Boland Park, Paarl",Wednesday 26 JANUARY,19:30 IST
8,ODI,INDIA V WEST INDIES 2022,"Narendra Modi Stadium, Ahmedabad",Sunday 06 FEBRUARY,FEBRUARY
9,ODI,INDIA V WEST INDIES 2022,"Sawai Mansingh Stadium, Jaipur",Wednesday 09 FEBRUARY,FEBRUARY
10,ODI,INDIA V WEST INDIES 2022,"Eden Gardens, Kolkata",Saturday 12 FEBRUARY,FEBRUARY
11,T20I,INDIA V WEST INDIES 2022,"Barabati Stadium, Cuttack",Tuesday 15 FEBRUARY,FEBRUARY
12,T20I,INDIA V WEST INDIES 2022,"ACA-VDCA Stadium, Visakhapatnam",Friday 18 FEBRUARY,FEBRUARY
13,T20I,INDIA V WEST INDIES 2022,"Greenfield Stadium, Thiruvananthapuram",Sunday 20 FEBRUARY,FEBRUARY
14,TEST,INDIA V SRI LANKA 2022,"M.Chinnaswamy Stadium, Bangalore",Friday 25 FEBRUARY,FEBRUARY
15,TEST,INDIA V SRI LANKA 2022,"Punjab Cricket Association Stadium, Mohali, Ch...",Saturday 05 MARCH,MARCH
16,T20I,INDIA V SRI LANKA 2022,"Punjab Cricket Association Stadium, Mohali, Ch...",Sunday 13 MARCH,MARCH
17,T20I,INDIA V SRI LANKA 2022,"Himachal Pradesh Cricket Association Stadium, ...",Tuesday 15 MARCH,MARCH
18,T20I,INDIA V SRI LANKA 2022,Bharat Ratna Shri Atal Bihari Vajpai Ekana Cri...,Friday 18 MARCH,MARCH
19,T20I,INDIA V SOUTH AFRICA 2022,"M. A. Chidambaram Stadium, Chennai",Thursday 09 JUNE,JUNE

3. Scrape the details of selenium exception from guru99.com.
Url = https://www.guru99.com/
You need to find following details:
A) Name
B) Description
Note: - From guru99 home page you have to reach to selenium exception handling page through code.

In [6]:
url = "https://www.guru99.com/"
page = requests.get(url)
print("Legality Response number from our URL is:", page) # to show the response output from the webpage
soup = BeautifulSoup(page.content)

driver = webdriver.Chrome('D:/Installed Software  2/chromedriver.exe')
driver.get(url)
driver.maximize_window()

error = driver.find_element_by_xpath('//*[@id="java_technologies"]/li[3]/a').get_attribute('href')
driver.get(error)
time.sleep(3)
exception = driver.find_element_by_xpath('/html/body/div[1]/div/div/div/main/div/article/div/div/table[5]/tbody/tr[34]/td[1]/a').get_attribute('href')
driver.get(exception)

Data = []
table = driver.find_elements_by_xpath("//table[@class='table table-striped']//td")
for i in table:
    try:
        Data.append(i.text)
    except NoSuchElementException:
        Data.append('-')

Name = []
for i in range(2,len(Data),2):
    Name.append(Data[i])

Description = []
for i in range(3,len(Data),2):
    Description.append(Data[i])

df=pd.DataFrame({"Exception name": Name, "Exception description": Description})
df

Legality Response number from our URL is: <Response [403]>

,Exception name,Exception description
0,ElementNotSelectableException,This Selenium exception occurs when an element...
1,NoSuchElementException,This Exception occurs if an element could not ...
2,NoSuchFrameException,This Exception occurs if the frame target to b...
3,NoAlertPresentException,This Exception occurs when you switch to no pr...
4,NoSuchWindowException,This Exception occurs if the window target to ...
5,StaleElementReferenceException,This Selenium exception occurs happens when th...
6,SessionNotFoundException,The WebDriver is acting after you quit the bro...
7,TimeoutException,Thrown when there is not enough time for a com...
8,WebDriverException,This Exception takes place when the WebDriver ...
9,ConnectionClosedException,This type of Exception takes place when there ...
10,ElementClickInterceptedException,The command may not be completed as the elemen...
11,ElementNotInteractableException,This Selenium exception is thrown when any ele...
12,ErrorInResponseException,This happens while interacting with the Firefo...
13,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
14,ImeActivationFailedException,This expectation will occur when IME engine ac...
15,ImeNotAvailableException,It takes place when IME support is unavailable.
16,InsecureCertificateException,Navigation made the user agent to hit a certif...
17,InvalidArgumentException,It occurs when an argument does not belong to ...
18,InvalidCookieDomainException,This happens when you try to add a cookie unde...
19,InvalidCoordinatesException,This type of Exception matches an interacting ...
20,InvalidElementStateExceptio,It occurs when command can’t be finished when ...
21,InvalidSessionIdException,This Exception took place when the given sessi...
22,InvalidSwitchToTargetException,This occurs when the frame or window target to...
23,JavascriptException,This issue occurs while executing JavaScript g...
24,JsonException,It occurs when you afford to get the session w...
25,NoSuchAttributeException,This kind of Exception occurs when the attribu...
26,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
27,NoSuchContextException,ContextAware does mobile device testing.
28,NoSuchCookieException,This Exception occurs when no cookie matching ...
29,NotFoundException,This Exception is a subclass of WebDriverExcep...
30,RemoteDriverServerException,This Selenium exception is thrown when the ser...
31,ScreenshotException,It is not possible to capture a screen.
32,SessionNotCreatedException,It happens when a new session could not be suc...
33,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
34,UnexpectedTagNameException,Happens if a support class did not get a web e...
35,UnhandledAlertException,This expectation occurs when there is an alert...
36,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
37,UnknownMethodException,This Exception happens when the requested comm...
38,UnreachableBrowserException,This Exception occurs only when the browser is...
39,UnsupportedCommandException,This occurs when remote WebDriver does n’t sen...

4. Scrape the details of State-wise GDP of India from statisticstime.com.
Url = http://statisticstimes.com/
You have to find following details:
A) Rank
B) State
C) GSDP
D) GSDP
E) Share
F) GDP($ billion)
Note: - From statisticstimes home page you have to reach to economy page through code.

In [7]:
url = "http://statisticstimes.com/"
page = requests.get(url)
print("Legality Response number from our URL is:", page) # to show the response output from the webpage
soup = BeautifulSoup(page.content)

driver = webdriver.Chrome('D:/Installed Software  2/chromedriver.exe')
driver.get(url)
driver.maximize_window()

economy = driver.find_element_by_xpath('/html/body/div[2]/div[1]/div[2]/div[2]/button')
economy.click()
time.sleep(2)
india = driver.find_element_by_xpath('/html/body/div[2]/div[1]/div[2]/div[2]/div/a[3]')
india.click()
time.sleep(2)

Legality Response number from our URL is: <Response [200]>

In [9]:
ind_eco = driver.find_element_by_xpath('/html/body/div[2]/div[2]/div[2]/ul/li[1]/a')
ind_eco.click()
time.sleep(2)

# Empty lists
Rank = []
State = []
GSDP1 = []
GSDP2  = []
Share = []
GDP_billion = []

try: # Scraping Rank
    for i in driver.find_elements_by_xpath("//table[@class='display dataTable']/tbody/tr/td[1]"):
        Rank.append(i.text)
except NoSuchElementException as e:
    print("No such element present")
    
try: # Scraping Name
    for i in driver.find_elements_by_xpath("//table[@class='display dataTable']/tbody/tr/td[2]"):
        State.append(i.text)
except NoSuchElementException as e:
    print("No such element present")
    
try: # Scraping GSDP1
    for i in driver.find_elements_by_xpath("//table[@class='display dataTable']/tbody/tr/td[3]"):
        GSDP1.append(i.text)
except NoSuchElementException as e:
    print("-")
    
try: # Scraping GSDP2
    for i in driver.find_elements_by_xpath("//table[@class='display dataTable']/tbody/tr/td[4]"):
        GSDP2.append(i.text)
except NoSuchElementException as e:
    print("-")

try: # Scraping share
    for i in driver.find_elements_by_xpath("//table[@class='display dataTable']/tbody/tr/td[5]"):
        Share.append(i.text)
except NoSuchElementException as e:
    print("-")    
    
try: # Scraping GDP billion
    for i in driver.find_elements_by_xpath("//table[@class='display dataTable']/tbody/tr/td[6]"):
        GDP_billion.append(i.text)
except NoSuchElementException as e:
    print("-")
    
# Creating data frame 
stats = pd.DataFrame({"Rank":Rank, "State":State, "GSDP (Cr INR at Current prices) (19-20)":GSDP1,
                      "GSDP (Cr INR at Current prices) (18-19)":GSDP2, "Share (18-19)":Share, 
                      "GDP ($ billion)":GDP_billion})
stats

,Rank,State,GSDP (Cr INR at Current prices) (19-20),GSDP (Cr INR at Current prices) (18-19),Share (18-19),GDP ($ billion)
0,1,Maharashtra,-,"2,632,792",13.94%,399.921
1,2,Tamil Nadu,"1,845,853","1,630,208",8.63%,247.629
2,3,Uttar Pradesh,"1,687,818","1,584,764",8.39%,240.726
3,4,Gujarat,-,"1,502,899",7.96%,228.290
4,5,Karnataka,"1,631,977","1,493,127",7.91%,226.806
...,...,...,...,...,...,...
61,29,Sikkim,"28,391","25,141",0.15%,"17,060"
62,30,Nagaland,-,"24,534",0.15%,-
63,31,Arunachal Pradesh,-,"22,488",0.13%,-
64,32,Mizoram,"24,424","20,947",0.13%,"17,797"
65,33,Andaman & Nicobar Islands,-,-,-,-

5. Scrape the details of trending repositories on Github.com.
Url = https://github.com/
You have to find the following details:
A) Repository title
B) Repository description
C) Contributors count
D) Language used

In [22]:
url = "https://github.com/"
page = requests.get(url)
print("Legality Response number from our URL is:", page) # to show the response output from the webpage
soup = BeautifulSoup(page.content)

driver = webdriver.Chrome('D:/Installed Software  2/chromedriver.exe')
driver.get(url)
driver.maximize_window()

Legality Response number from our URL is: <Response [200]>

In [24]:
explore = driver.find_element_by_xpath("/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/summary")
explore.click()
time.sleep(2)

trending = driver.find_element_by_xpath("/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/div/ul/li[5]/a")
trending.click()
time.sleep(2)

# Empty list
Repository = []
Repository_des = []
Contributors = []
Language = []

try: # Scraping repository
    for i in driver.find_elements_by_xpath("//h1[@class='h3 lh-condensed']/a"):
        Repository.append(i.text)
except NoSuchElementException as e:
    print("-")
    
try: # Scraping Repository description
    for i in driver.find_elements_by_xpath("//p[@class='col-9 color-fg-muted my-1 pr-4']"):
        Repository_des.append(i.text)
except NoSuchElementException as e:
    print("-")

try: # Scraping Contributors count
    for i in driver.find_elements_by_xpath("//*[@id='js-pjax-container']/div[3]/div/div[2]/article/div[2]/a[2]"):
        Contributors.append(i.text)
except NoSuchElementException as e:
    print("-")   
    
try: # Scraping language
    for i in driver.find_elements_by_xpath("//span[@class='d-inline-block ml-0 mr-3']"):
        Language.append(i.text)
except NoSuchElementException as e:
    print("-")

# Creating data frame 
a = {"Repository title":Repository[:10],"Repository description":Repository_des[:10],"Contributors count": Contributors[:10],"Language used": Language[:10]}
df = pd.DataFrame.from_dict(a, orient='index')
df = df.transpose()
df

,Repository title,Repository description,Contributors count,Language used
0,freqtrade / freqtrade,"Free, open source crypto trading bot","3,159",Python
1,codenotary / immudb,"immudb - world’s fastest immutable database, b...",177,Go
2,bytedance / btrace,🔥🔥 btrace(AKA RheaTrace) is a high performance...,42,Kotlin
3,ethereum / EIPs,The Ethereum Improvement Proposal repository,"3,064",Solidity
4,google / googletest,GoogleTest - Google Testing and Mocking Framework,"8,122",C++
5,vitest-dev / vitest,A Vite-native test framework. It's fast!,30,TypeScript
6,EmbarkStudios / kajiya,💡 Experimental real-time global illumination r...,11,Rust
7,RedisJSON / RedisJSON,RedisJSON - a JSON data type for Redis,191,Rust
8,prisma / prisma,Next-generation ORM for Node.js & TypeScript |...,663,TypeScript
9,LunarVim / Neovim-from-scratch,A Neovim config designed from scratch to be un...,67,Lua

6. Scrape the details of top 100 songs on billiboard.com.
Url = https:/www.billboard.com/
You have to find the following details:
A) Song name
B) Artist name
C) Last week rank
D) Peak rank
E) Weeks on board
Note: - From the home page you have to click on the charts option then hot 100-page link through code.

In [26]:
url = "https://www.billboard.com/"
page = requests.get(url)
print("Legality Response number from our URL is:", page) # to show the response output from the webpage
soup = BeautifulSoup(page.content)

driver = webdriver.Chrome('D:/Installed Software  2/chromedriver.exe')
driver.get(url)
driver.maximize_window()

hot_100 = driver.find_element_by_xpath('//*[@id="main-wrapper"]/header/div[2]/div/nav/ul/li[1]/a')
hot_100.click()
time.sleep(2)

Song_name=[i.text for i in driver.find_elements_by_xpath("//span[@class='chart-element__information']/span[@class='chart-element__information__song text--truncate color--primary']")]

Artist_name=[i.text for i in driver.find_elements_by_xpath("//span[@class='chart-element__information']/span[@class='chart-element__information__artist text--truncate color--secondary']")]

Last_week_rank=[i.text for i in driver.find_elements_by_xpath("//div[@class='chart-element__metas chart-element__metas--large display--flex flex--y-center']/div[@class='chart-element__meta text--center color--secondary text--last']")]

Peak_rank=[i.text for i in driver.find_elements_by_xpath("//div[@class='chart-element__metas chart-element__metas--large display--flex flex--y-center']/div[@class='chart-element__meta text--center color--secondary text--peak']")]

Weeks_on_board=[i.text for i in driver.find_elements_by_xpath("//div[@class='chart-element__metas chart-element__metas--large display--flex flex--y-center']/div[@class='chart-element__meta text--center color--secondary text--week']")]

# Creating data frame
Songs=pd.DataFrame({"SONG NAME":Song_name, "ARTIST":Artist_name, "LAST WEEK RANK":Last_week_rank,
                    "PEAK RANK":Peak_rank, "WEEK ON BORD":Weeks_on_board})
Songs

Legality Response number from our URL is: <Response [200]>

Empty DataFrame
Columns: [SONG NAME, ARTIST, LAST WEEK RANK, PEAK RANK, WEEK ON BORD]
Index: []

7. Scrape the details of Data science recruiters from naukri.com.
Url = https://www.naukri.com/
You have to find the following details:
A) Name
B) Designation
C) Company
D) Skills they hire for
E) Location
Note: - From naukri.com homepage click on the recruiters option and the on the search pane type Data science and
click on search. All this should be done through code

In [41]:
url = "https://www.naukri.com/"
driver = webdriver.Chrome('D:/Installed Software  2/chromedriver.exe')
driver.get(url)
driver.maximize_window()
time.sleep(6)

# entering “Data Analyst” in “Skill,Designations,Companies” field and enter “Bangalore” in “enter the location” field.
search_field_designation=driver.find_element_by_id("qsb-keyword-sugg") #job search bar
search_field_location=driver.find_element_by_id('qsb-location-sugg') #location search bar
search_field_designation.send_keys("Data Analyst")
search_field_location.send_keys("Bangalore")


# clicking the search button
search_button=driver.find_element_by_xpath("//div[@class='search-btn']/button")
search_button.click()


time.sleep(4)

name = []
designation = []
company = []
skills = []
location = []

# fetching Names
for i in driver.find_elements_by_xpath("//span[@class='fl ellipsis']"):
    name.append(i.text)
    
# fetching Designation
for i in driver.find_elements_by_xpath("//span[@class='ellipsis clr']"):
    designation.append(i.text)

# fetching Company names
for i in driver.find_elements_by_xpath("//div[@class='vcard']//p[1]/a[2]"):
    company.append(i.text)
    
# fetching  Skills
for i in driver.find_elements_by_xpath("//div[@class='hireSec highlightable']"):
    try:
        if i.text == "Not Specified": raise NoSuchElementException
        skills.append(i.text)
    except NoSuchElementException:
        skills.append('-')
                
# fetching Locations
for i in driver.find_elements_by_xpath("//div[@class='vcard']//p[1]//span"):
    location.append(i.text)
    
# Creating a dataframe
data = list(zip(name, designation, company, skills, location))
df = pd.DataFrame(data, columns = ["Name", "Designation", "Company Name", "Skills they hire for", "Location"])
df

Empty DataFrame
Columns: [Name, Designation, Company Name, Skills they hire for, Location]
Index: []

8. Scrape the details of Highest selling novels.
Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-greycompare/
You have to find the following details:
A) Book name
B) Author name
C) Volumes sold
D) Publisher
E) Genre

In [42]:
url = "https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare/"
page = requests.get(url)
print("Legality Response number from our URL is:", page) # to show the response output from the webpage
soup = BeautifulSoup(page.content)

driver = webdriver.Chrome('D:/Installed Software  2/chromedriver.exe')
driver.get(url)
driver.maximize_window()

Book_name = []
Author_name = []
Volume_sold = []
Publisher = []
Genre = []

try: # Scraping Book name
    for i in driver.find_elements_by_xpath("//div[@class='embed block']/table/tbody/tr/td[2]"):
        Book_name.append(i.text)
except NoSuchElementException as e:
    print("-")
    
try: # Scraping Author name
    for i in driver.find_elements_by_xpath("//div[@class='embed block']/table/tbody/tr/td[3]"):
        Author_name.append(i.text)
except NoSuchElementException as e:
    print("-")
        
try: # Scraping Volume sold
    for i in driver.find_elements_by_xpath("//div[@class='embed block']/table/tbody/tr/td[4]"):
        Volume_sold.append(i.text)
except NoSuchElementException as e:
    print("-")
    
try: # Scraping Publisher
    for i in driver.find_elements_by_xpath("//div[@class='embed block']/table/tbody/tr/td[5]"):
        Publisher.append(i.text)
except NoSuchElementException as e:
    print("-") 
    
try: # Scraping Genre
    for i in driver.find_elements_by_xpath("//div[@class='embed block']/table/tbody/tr/td[6]"):
        Genre.append(i.text)
except NoSuchElementException as e:
    print("-")
    
# Creating data frame 
Books=pd.DataFrame({'Book Name': Book_name, 'Author Name': Author_name, 'Volume Sold': Volume_sold,
                    'Publisher': Publisher, 'Genre' : Genre})
Books

Legality Response number from our URL is: <Response [200]>

,Book Name,Author Name,Volume Sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

9. Scrape the details most watched tv series of all time from imdb.com.
Url = https://www.imdb.com/list/ls095964455/
You have to find the following details:
A) Name
B) Year span
C) Genre
D) Run time
E) Ratings
F) Votes

In [44]:
url = "https://www.imdb.com/list/ls095964455/"
page = requests.get(url)
print("Legality Response number from our URL is:", page) # to show the response output from the webpage
soup = BeautifulSoup(page.content)

driver = webdriver.Chrome('D:/Installed Software  2/chromedriver.exe')
driver.get(url)
driver.maximize_window()

name = []
year = []
genre = []
runtime = []
rating = []
vote = []

try: # Scraping Name
    for i in driver.find_elements_by_xpath("//h3[@class='lister-item-header']/a"):
        name.append(i.text)
except NoSuchElementException as e:
    print("-")
    
try: # Scraping Year span
    for i in driver.find_elements_by_xpath("//span[@class='lister-item-year text-muted unbold']"):
        year.append(i.text)
except NoSuchElementException as e:
    print("-")
        
try: # Scraping Genre
    for i in driver.find_elements_by_xpath("//div[@class='lister-item-content']/p/span[5]"):
        genre.append(i.text)
except NoSuchElementException as e:
    print("-")
    
try: # Scraping Run time
    for i in driver.find_elements_by_xpath("//div[@class='lister-item-content']/p/span[3]"):
        runtime.append(i.text)
except NoSuchElementException as e:
    print("-") 
    
try: # Scraping Ratings
    for i in driver.find_elements_by_xpath("//div[@class='ipl-rating-star small']/span[2]"):
        rating.append(i.text)
except NoSuchElementException as e:
    print("-")
    
try: # Scraping votes
    for i in driver.find_elements_by_xpath("//div[@class='lister-item-content']/p[4]/span[2]"):
        vote.append(i.text)
except NoSuchElementException as e:
    print("-")

# Creating a dataframe 
imdb=pd.DataFrame({'Name':name, 'Year Span':year, 'Genre':genre, 'Run Time':runtime, 'Ratings':rating, 'Votes':vote})
imdb

Legality Response number from our URL is: <Response [200]>

,Name,Year Span,Genre,Run Time,Ratings,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"1,917,179"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"942,950"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.2,"917,804"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.5,"274,790"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"235,184"
...,...,...,...,...,...,...
95,Reign,(2013–2017),"Drama, Fantasy",42 min,7.5,"46,857"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"57,637"
97,Criminal Minds,(2005–2020),"Crime, Drama, Mystery",42 min,8.1,"181,741"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"37,994"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"215,773"

10. Details of Datasets from UCI machine learning repositories.
Url = https://archive.ics.uci.edu/
You have to find the following details:
A) Dataset name
B) Data type
C) Task
D) Attribute type
E) No of instances
F) No of attribute
G) Year
Note: - from the home page you have to go to the ShowAllDataset page through code.

In [45]:
url = "https://archive.ics.uci.edu/"
page = requests.get(url)
print("Legality Response number from our URL is:", page) # to show the response output from the webpage
soup = BeautifulSoup(page.content)

driver = webdriver.Chrome('D:/Installed Software  2/chromedriver.exe')
driver.get(url)
driver.maximize_window()

respository=driver.find_element_by_xpath("//span[@class='normal']/b/a")
respository.click()
    
Name=[]
Type=[]
Task=[]
Attribute=[]
No_of_Instance=[]
No_of_Attribute=[]
Year=[]

# Scrapping data for dataset name
try:
    names=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[1]/table/tbody/tr/td[2]/p/b/a")
    for i in names:
        Name.append(i.text)
except NoSuchElementException:
    Name.append('-')
    
# Scrapping data for data type
try:
    types=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[2]")
    for i in types[1:]:
        Type.append(i.text)
except NoSuchElementException:
    Type.append('-')
    
# Scrapping data for default task
try:
    task=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[3]")
    for i in task[1:]:
        Task.append(i.text)
except NoSuchElementException:
    Task.append('-')
        
# Scrapping data for attribute type
try:
    attribute=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[4]")
    for i in attribute[1:]:
        Attribute.append(i.text)
except NoSuchElementException:
    Attribute.append('-')
       
# Scrapping data for number of instances
try:
    instance=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[5]")
    for i in instance[1:]:
        No_of_Instance.append(i.text)
except NoSuchElementException:
    No_of_Instance.append('-')
        
# Scrapping data for number of attributes
try:
    attribute_no=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[6]")
    for i in attribute_no[1:]:
        No_of_Attribute.append(i.text)
except NoSuchElementException:
    No_of_Attribute.append('-')
        
# Scrapping data for the year details
try:
    year=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[7]")
    for i in year[1:]:
        Year.append(i.text)
except NoSuchElementException:
    Year.append('-')
    
# Creating the dataframe
df=pd.DataFrame({"Dataset Name":Name, "Data Type":Type, "Default Task":Task, "Attribute Type":Attribute, 
                 "No of instances":No_of_Instance, "No of atrributes":No_of_Attribute, "Year":Year})
df

Legality Response number from our URL is: <Response [200]>

,Dataset Name,Data Type,Default Task,Attribute Type,No of instances,No of atrributes,Year
0,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
1,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
2,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,
3,Anonymous Microsoft Web Data,,Recommender-Systems,Categorical,37711,294,1998
4,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
...,...,...,...,...,...,...,...
617,Influenza outbreak event prediction via Twitte...,Multivariate,Classification,"Integer, Real",75840,525,2020
618,Turkish Music Emotion Dataset,Multivariate,Classification,"Integer, Real",400,50,2020
619,Maternal Health Risk Data Set,,Classification,,1014,7,2020
620,Room Occupancy Estimation,"Multivariate, Time-Series",Classification,Real,10129,16,2021
621,Image Recognition Task Execution Times in Mobi...,Univariate,Regression,Real,4000,2,2021